[package]
name = "highrust-cli"
version = "0.1.0"
edition = "2021"
authors = ["HighRust Core Engineering"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
highrust-transpiler = { path = "../highrust-transpiler" }
notify = "8"